### ISSUE TITLE
SIGs are case-sensitive

### ISSUE THREAD

**Issue by taliyahpottruff** [The-Valley-Discord/blimp#18]
`sig! join` and `sig! leave` work while `sig! Join` and `sig! Leave` do not.

**Comment by taliyahpottruff** [comment]
Seems like the solution is quite simple but at the cost of some performance:

https://stackoverflow.com/questions/48120312/how-to-make-a-command-case-insensitive-in-discord-py

**Comment by deingithub** [comment]
We already use that option, see here:

https://github.com/The-Valley-Discord/blimp/blob/bece546c5b86aeb812bfc60da3621a7e936a2006/blimp/__main__.py#L34

I'll do some investigating later today why this is a problem; i could imagine it's related to the fake prefix function in `customizations.py`.

**Comment by deingithub** [comment]
Fixed in a6a255539ab92bdf13bd47ae4a3c5fd15fabae84
